/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import java.util.ArrayList;
import java.util.List;

public class App {

  public static void main(String[] args) {
    Graph graph = new Graph();

    graph.addVertex("alaa");
    graph.addVertex("fares");
    graph.addVertex("a");
    graph.addVertex("f");

    graph.addEdge("alaa","fares");
    graph.addEdge("alaa", "f");
    graph.addEdge("alaa", "a");
    graph.addEdge("a","f");
    graph.addEdge("fares","alaa");

    System.out.println(graph.printGraph());



    System.out.println();
    System.out.println(graph.getVertices());

    System.out.println();
    System.out.println(graph.getNeighbors("hello"));


    System.out.println();
    System.out.println(graph.size());


    Graph graph1 = new Graph();

    graph1.addVertex("alaa");
    graph1.addVertex("hello");
    graph1.addVertex("from");
    graph1.addVertex("graph");

    graph1.addEdge("alaa", "hello");
    graph1.addEdge("hello", "from");
    graph1.addEdge("hello", "graph");
    graph1.addEdge("from", "graph");



    System.out.println(graph1.breadthTraverse( "alaa"));


//        <<< Code Challenge 37 >>>

    Graph graph2 = new Graph();

    graph2.addVertex("Pandora");
    graph2.addVertex("Arendelle");
    graph2.addVertex("Metroville");
    graph2.addVertex("Monstroplolis");
    graph2.addVertex("Narnia");
    graph2.addVertex("Naboo");

    graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
    graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
    graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
    graph2.addEdgeWithWeight("Metroville", "Narnia",37);
    graph2.addEdgeWithWeight("Metroville", "Naboo",26);
    graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
    graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
    graph2.addEdgeWithWeight("Narnia", "Naboo",250);

    List<String> cities = new ArrayList<>();
    cities.add("Pandora");
    cities.add("Narnia");



    List<String> cities2 = new ArrayList<>();
    cities2.add("Pandora");
    cities2.add("Arendelle");

    System.out.println("Trip 1 :  "+graph2.businessTrip(graph2,cities));
    System.out.println("Trip 2 :  "+graph2.businessTrip(graph2,cities2));





    Graph graph3 = new Graph();

    graph3.addVertex("A");
    graph3.addVertex("B");
    graph3.addVertex("C");
    graph3.addVertex("D");
    graph3.addVertex("E");
    graph3.addVertex("F");
    graph3.addVertex("G");
    graph3.addVertex("H");

    graph3.addEdge("A", "D");
    graph3.addEdge("A", "B");
    graph3.addEdge("B", "D");
    graph3.addEdge("B", "C");
    graph3.addEdge("C", "G");

    System.out.println("Depth first ---> " + graph3.depthFirstTraverse("A"));





  }
}
